/*
 * Copyright 2012-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// ********RoostGPT********
/*
Test generated by RoostGPT for test spring-petclinic using AI Type Azure Open AI and AI Model gpt-4.1

ROOST_METHOD_HASH=getVetList_89589e59e0
ROOST_METHOD_SIG_HASH=getVetList_f4b55b5394

Retrieve List When Field Is Already Initialized,Multiple Calls Without Assignment Return The Same Instance
*/

// ********RoostGPT********

package org.springframework.samples.petclinic.vet;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.*;

public class VetsGetVetListTest {

	private Vets vets;

	@BeforeEach
	public void setUp() {
		vets = new Vets();
	}

	@Test
	@Tag("valid")
	public void testRetrieveListWhenFieldIsAlreadyInitialized() {
		List<Vet> dummyList = new ArrayList<>();
		// Simulate user assignment of vets via getVetList, since no setter or direct
		// field access.
		dummyList.add(new Vet());
		vets.getVetList().add(dummyList.get(0)); // list initialized and mutated via
													// public API
		List<Vet> vetList = vets.getVetList();
		assertEquals(dummyList.size(), ((List<Vet>) vetList).size());
		assertSame(dummyList.get(0), ((List<Vet>) vetList).get(0)); // Ensure same
																	// instance is
																	// returned
	}

	@Test
	@Tag("boundary")
	public void testMultipleCallsWithoutAssignmentReturnTheSameInstance() {
		List<Vet> firstCall = vets.getVetList();
		List<Vet> secondCall = vets.getVetList();
		assertSame(firstCall, secondCall); // should be the same instance
		assertTrue(((List<Vet>) firstCall).isEmpty());
	}

}